# fly.toml app configuration file generated for api-acme-com on 2024-05-25T09:11:28+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-acme-com'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[[services]]
  protocol = 'tcp'
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '10s'
    timeout = '2s'
