// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package queries

import (
	"database/sql"
)

type ApiKey struct {
	ID        string
	UserID    string
	Key       string
	CreatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type User struct {
	ID              string
	FirstName       sql.NullString
	LastName        sql.NullString
	Email           string
	EmailHash       string
	EmailVerifiedAt sql.NullTime
	Password        string
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
}
